import fs from "fs-extra";
import path from "path";

const GENERATED_ROOT = path.join(process.cwd(), "generated");

const sanitizeProjectName = (name) => {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
};

export const generateProject = async (dsl) => {
  const safeProjectName = sanitizeProjectName(
    dsl?.projectName || dsl?.app?.name || "evoke-generated-app"
  );

  const projectPath = path.join(GENERATED_ROOT, safeProjectName);

  await fs.ensureDir(projectPath);
  await fs.ensureDir(path.join(projectPath, "client"));
  await fs.ensureDir(path.join(projectPath, "server"));
  await fs.ensureDir(path.join(projectPath, "database"));
  await fs.ensureDir(path.join(projectPath, "docker"));

  await fs.writeJson(
    path.join(projectPath, "package.json"),
    {
      name: safeProjectName,
      version: "1.0.0",
      private: true,
      description: dsl?.app?.description || "Generated by EVOKE",
      scripts: {
        dev: "echo \"Run client and server separately\""
      }
    },
    { spaces: 2 }
  );

  await fs.writeJson(
    path.join(projectPath, "evoke.dsl.json"),
    dsl,
    { spaces: 2 }
  );

  await fs.writeFile(
    path.join(projectPath, "README.md"),
`# ${dsl?.app?.name || safeProjectName}

Generated by EVOKE.

## Description

${dsl?.app?.description || "No description provided."}

## Structure

\`\`\`
client/
server/
database/
docker/
README.md
.env.example
evoke.dsl.json
\`\`\`

## Notes

This is the first generated scaffold. The next EVOKE milestones will progressively generate real frontend, backend, database, and Docker files.
`
  );

  await fs.writeFile(
    path.join(projectPath, ".env.example"),
`# Client
VITE_API_URL=http://localhost:5000/api

# Server
PORT=5000
DATABASE_URL=
JWT_SECRET=
`
  );

  await fs.writeFile(
    path.join(projectPath, "client", "README.md"),
`# Client

Frontend application generated by EVOKE.

Planned stack:
- React / Next.js / Angular depending on DSL
- TypeScript
- Responsive UI
`
  );

  await fs.writeFile(
    path.join(projectPath, "server", "README.md"),
`# Server

Backend application generated by EVOKE.

Planned stack:
- Express / NestJS / Spring Boot depending on DSL
- REST API
- Authentication if requested
`
  );

  await fs.writeFile(
    path.join(projectPath, "database", "README.md"),
`# Database

Database schema generated by EVOKE.

Planned databases:
- MongoDB
- PostgreSQL
- MySQL
`
  );

  await fs.writeFile(
    path.join(projectPath, "docker", "README.md"),
`# Docker

Docker configuration generated by EVOKE.
`
  );

  return {
    projectPath,
    projectName: safeProjectName,
    files: [
      "package.json",
      "evoke.dsl.json",
      "README.md",
      ".env.example",
      "client/README.md",
      "server/README.md",
      "database/README.md",
      "docker/README.md"
    ]
  };
};