import fs from "fs-extra";
import path from "path";

const GENERATED_ROOT = path.join(process.cwd(), "generated");

const sanitizeProjectName = (name = "") => {
  const sanitized = name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return sanitized || "evoke-generated-app";
};

const detectLanguage = (filePath) => {
  const fileName = path.basename(filePath).toLowerCase();
  const extension = path.extname(filePath).toLowerCase();

  if (fileName === ".env.example") {
    return "properties";
  }

  const languageMap = {
    ".json": "json",
    ".md": "markdown",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".css": "css",
    ".html": "html",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".sql": "sql",
    ".java": "java",
    ".xml": "xml",
  };

  return languageMap[extension] || "text";
};

const writeTextFile = async (projectPath, relativePath, content) => {
  const absolutePath = path.join(projectPath, relativePath);

  await fs.ensureDir(path.dirname(absolutePath));
  await fs.writeFile(absolutePath, content, "utf-8");
};

const writeJsonFile = async (projectPath, relativePath, content) => {
  const absolutePath = path.join(projectPath, relativePath);

  await fs.ensureDir(path.dirname(absolutePath));
  await fs.writeJson(absolutePath, content, { spaces: 2 });
};

const collectGeneratedFiles = async (projectPath) => {
  const files = [];

  const walk = async (currentPath) => {
    const entries = await fs.readdir(currentPath, {
      withFileTypes: true,
    });

    for (const entry of entries) {
      const absolutePath = path.join(currentPath, entry.name);
      const relativePath = path
        .relative(projectPath, absolutePath)
        .replaceAll("\\", "/");

      if (entry.isDirectory()) {
        await walk(absolutePath);
        continue;
      }

      const content = await fs.readFile(absolutePath, "utf-8");

      files.push({
        path: relativePath,
        content,
        language: detectLanguage(relativePath),
      });
    }
  };

  await walk(projectPath);

  return files.sort((a, b) => a.path.localeCompare(b.path));
};

export const generateProject = async (dsl) => {
  const safeProjectName = sanitizeProjectName(
    dsl?.projectName || dsl?.app?.name || "evoke-generated-app"
  );

  const appName =
    dsl?.app?.name ||
    dsl?.projectName ||
    safeProjectName;

  const description =
    dsl?.app?.description ||
    dsl?.description ||
    "Full-stack application generated by EVOKE.";

  const frontend = dsl?.frontend || "react-vite";
  const backend = dsl?.backend || "express";
  const database = dsl?.database || "mongodb";

  const projectPath = path.join(GENERATED_ROOT, safeProjectName);

  await fs.remove(projectPath);
  await fs.ensureDir(projectPath);

  await writeJsonFile(projectPath, "package.json", {
    name: safeProjectName,
    version: "1.0.0",
    private: true,
    description,
    scripts: {
      dev: 'echo "Run client and server separately"',
    },
  });

  await writeJsonFile(projectPath, "evoke.dsl.json", dsl);

  await writeTextFile(
    projectPath,
    "README.md",
`# ${appName}

Generated by EVOKE.

## Description

${description}

## Selected stack

- Frontend: ${frontend}
- Backend: ${backend}
- Database: ${database}

## Structure

\`\`\`
client/
server/
database/
docker/
README.md
.env.example
evoke.dsl.json
\`\`\`
`
  );

  await writeTextFile(
    projectPath,
    ".env.example",
`VITE_API_URL=http://localhost:5000/api
PORT=5000
DATABASE_URL=
JWT_SECRET=
`
  );

  await writeTextFile(
    projectPath,
    "client/README.md",
`# Client

Selected frontend: ${frontend}

The AI Frontend Agent will generate the complete frontend implementation here.
`
  );

  await writeTextFile(
    projectPath,
    "server/README.md",
`# Server

Selected backend: ${backend}

The AI Backend Agent will generate the complete backend implementation here.
`
  );

  await writeTextFile(
    projectPath,
    "database/README.md",
`# Database

Selected database: ${database}

The AI Database Agent will generate the schema and persistence layer here.
`
  );

  await writeTextFile(
    projectPath,
    "docker/README.md",
`# Docker

Container configuration will be generated after application validation.
`
  );

  const files = await collectGeneratedFiles(projectPath);

  return {
    projectPath,
    projectName: safeProjectName,
    files,
  };
};