import fs from "fs-extra";
import path from "path";

export const generateProject = async (dsl) => {
  const projectPath = path.join(
    process.cwd(),
    "generated",
    dsl.projectName
  );

  await fs.ensureDir(projectPath);
  await fs.ensureDir(path.join(projectPath, "src"));

  await fs.writeJson(
    path.join(projectPath, "package.json"),
    {
      name: dsl.projectName,
      version: "1.0.0",
      private: true
    },
    { spaces: 2 }
  );

  await fs.writeFile(
    path.join(projectPath, "README.md"),
`# ${dsl.app.name}

Generated by EVOKE

Description:
${dsl.app.description}
`
  );

  await fs.writeFile(
    path.join(projectPath, "src", "App.jsx"),
`export default function App() {
  return (
    <div>
      <h1>${dsl.app.name}</h1>
      <p>${dsl.app.description}</p>
    </div>
  );
}
`
  );

  await fs.writeFile(
    path.join(projectPath, "src", "main.jsx"),
`import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
`
  );

  return projectPath;
};